name: 'Build'
description: 'Builds the project into an executable and runs tests'
inputs:
  generator:
    description: 'The CMake generator to use'
    required: false
    default: ''

runs:
  using: 'composite'

  steps:
    - run: |
        mkdir release
        mkdir -p temp && cd temp
        cmake -DCMAKE_BUILD_TYPE=Release -G "${{inputs.generator}}" ..
        cmake --build . --config=Release
        cmake --build . --config=Release --target test
        mv ./**/benchmark* ../release
        cd ..
        rm -rf ./temp
      shell: bash

    - run: |
        mkdir debug
        mkdir -p temp && cd temp
        cmake -DCMAKE_BUILD_TYPE=Debug -G "${{inputs.generator}}" ..
        cmake --build . --config=Debug
        mv ./**/benchmark* ../debug
        cd ..
        rm -rf temp
      shell: bash
