name: Run benchmark

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Build executable
      run: |
        mkdir build && cd build
        cmake ..
        make
        make test
    
    - name: Run benchmark
      run: |
        ./build/sorting
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: out
