name: Run benchmark

on: workflow_dispatch

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build executable
        uses: .github/actions/build

      - name: Run benchmark
        run: |
          ./build/sorting
    
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: out
