name: Run benchmark

on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Program arguments'
        required: false
        default: ''

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build executable
        uses: ./.github/actions/build-ubuntu

      - name: Run benchmark
        run: |
          ./build/sorting ${{ github.event.inputs.arguments }}
    
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: out
