name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2016, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build executable
        uses: ./.github/actions/build
      
      - name: Consolidate builds
        shell: bash
        run: |
          mkdir build
          mv release build
          mv debug build

      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: build
