name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            os-name: windows
            generator: 'Visual Studio 16 2019'
          - os: ubuntu-latest
            os-name: ubuntu
            generator: 'Unix Makefiles'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Build executable on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ./.github/actions/build-windows
        with:
          generator: ${{ matrix.generator }}

      - name: Build executable on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/build-ubuntu
        with:
          generator: ${{ matrix.generator }}
      
      - name: Consolidate builds
        shell: bash
        run: |
          mkdir build
          mv release build
          mv debug build

      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os-name }}
          path: build
